# sqlite-vec ships no type information; these are the signatures of its
# __init__.py at the pinned release (register_numpy, which needs numpy, left out).
import sqlite3

__version__: str
__version_info__: tuple[str, ...]

def loadable_path() -> str: ...
def load(conn: sqlite3.Connection) -> None: ...
def serialize_float32(vector: list[float]) -> bytes: ...
def serialize_int8(vector: list[int]) -> bytes: ...
